spring:
  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: clientIdTest
            client-secret: clientSecretTest
          facebook:
            client-id: 1858496107618513
            client-secret: a0167fe7518a6ba87912c7bb579150bb
custom:
  oauth2:
    kakao:
      client-id: f2f840cd0486149758b592c68a8726d1